config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :posts
  root 'home#index'
  get 'home/about'
  get 'home/allposts'
  get 'home/whatshot'
  put '/post/:id/like', to: 'posts#like', as: 'like'
  put '/post/:id/dislike', to: 'posts#dislike', as: 'dislike'
  #get 'home/useremails'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :post

   validates :user_id, uniqueness: {scope: :post_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to:user
	has_many:likes
	has_many:dislikes

	def isliked(user)
		!!self.likes.find{|like|like.user_id == user.id}
	end

	def isdisliked(user)
		!!self.dislikes.find{|dislike|dislike.user_id==user.id}
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_many:posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
  def whatshot
  	@posts = Post.order(params[:sort]).reverse_order
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show,:index]
  before_action :right_user, only:[:edit,:update,:destroy]
  # GET /posts or /posts.json

  def like
    @post = Post.all.find(params[:id])
    temp = @post.upvotes+1
    if @post.isdisliked(current_user)
      temp2 = @post.downvotes - 1
      @post.update(upvotes: temp, downvotes: temp2)
      Dislike.find_or_create_by(user_id: current_user.id).destroy
    else
      @post.update(upvotes: temp)
    end
    Like.create(user_id: current_user.id, post_id: @post.id)

    redirect_back(fallback_location: home_whatshot_path)

    #respond_to do |format|
      #format.js {render inline: "location.reload();" }
      #format.html{ redirect_to home_whatshot_path }
    #end
    
  end

  def dislike
    @post = Post.all.find(params[:id])
    temp=@post.downvotes+1
    if @post.isliked(current_user)
      temp2 = @post.upvotes - 1
      @post.update(upvotes:temp2,downvotes:temp)
      Like.find_or_create_by(user_id:current_user.id,post_id:@post.id).destroy
    else
      @post.update(downvotes: temp)
    end

    Dislike.create(user_id:current_user.id, post_id:@post.id)

    redirect_back(fallback_location: home_whatshot_path)
  end


  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  def right_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not authorized." if @post.nil?
  end
  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :upvotes, :downvotes, :updatedat, :userid)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark position-absolute top-100 start-50 translate-middle">
  <div class="container-fluid">
    <%= link_to 'Bye bye',root_path, class:"navbar-brand fw-bold " %>
    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    </div>
  </div>
</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow p-3 mb-5 rounded">
  <div class="container-fluid">
    <div class="navbar-brand fw-bold">
        Forum
    </div>
    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!--<a class="nav-link fw-light active " href="#">Whats  <span class ="fw-light active text-danger">HOT ?</span></a>-->
          <%= link_to "What's Hot?",home_whatshot_path ,class:"nav-link fw-light active text-danger " %>

        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'History',posts_path, class:"nav-link fw-light active"  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New Post',new_post_path, class:"nav-link fw-light active"  %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'About Creator ',home_about_path, class:"nav-link fw-light active"  %>
        </li>
      </ul>
      <% if user_signed_in? %>

       <span class="navbar-text  fst-italic">
          &emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp;&emsp; &emsp;&emsp;
          Lets see whats cooking. Shall we?
      </span>

        <ul class="navbar-nav text-end me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
            <a class="nav-link fw-light active dropdown-toggle fw-bolder" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.email.length <18  %>
                <%= current_user.email %>
              <% else %>
                <%= current_user.email[0,18] %> ..
              <% end %>
            </a>
            <ul class="dropdown-menu bg-dark shadow mb-2 rounded" aria-labelledby="navbarDropdown">
              <%= link_to ' Edit User',edit_user_registration_path, class:"nav-link fw-light"  %>
              <!--<%= link_to ' Log In', new_user_session_path, class:"nav-link fw-light"  %>-->
              <%= link_to ' Log Out',  destroy_user_session_path,method: :delete, class:"nav-link fw-light"  %>
            </ul>
          </li>
        </ul>
      <% else %>

       <span class="navbar-text  fst-italic">
          &emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;&emsp; &emsp; &emsp;  &emsp; &emsp; &emsp;
          Lets see whats cooking. Shall we?
      </span>

      <ul class="navbar-nav text-end me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
            <a class="nav-link fw-light active dropdown-toggle fw-bolder" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Your Account
            </a>
            <ul class="dropdown-menu bg-dark shadow mb-2 rounded" aria-labelledby="navbarDropdown">
              <%= link_to ' Sign Up',new_user_registration_path, class:"nav-link fw-light"  %>
              <%= link_to ' Log In', new_user_session_path, class:"nav-link fw-light"  %>
              <!--<%= link_to ' Log Out',  destroy_user_session_path,method: :delete, class:"nav-link fw-light"  %>-->
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Sudershan Sridhar created this forum</h1>

app/views/home/allposts.html.erb
<h1>Post List</h1>
<table>
  <tr>
    <th><%= link_to "Title", :sort => "title"%> </th>
    <th><%= link_to "Content", :sort => "content"%> </th>
    <th><%= link_to "Likes", :sort => "upvotes"%> </th>
    <th><%= link_to "Dislikes", :sort => "downvotes"%> </th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title%></td>
    <td><%=post.content %></td><td>
    <td>  <%=post.upvotes %></td>
    <td>  <%=post.downvotes %></td>
  </tr>
  <% end %>
  </table>

app/views/home/index.html.erb
<h1>Lets go! Forum gang!</h1>
<p>Aight GG! 4 hrs here i come!</p>

app/views/home/whatshot.html.erb
<h1>What's <span class="text-danger">Hot </span>?</h1>

<div class="dropdown text-end">
  <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Order by
  </button>
  <ul class="dropdown-menu text-center" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" ><%= link_to "Latest", :sort => "created_at"%></a></li>
    <li><a class="dropdown-item" ><%= link_to "Content", :sort => "content"%></a></li>
    <li><a class="dropdown-item"><%= link_to "Likes", :sort => "upvotes"%></a></li>
    <li><a class="dropdown-item" ><%= link_to "Dislikes", :sort => "downvotes"%></a></li>
  </ul>
</div>

<br/>
<br/>
<% @posts.each do |post| %>
  <div class="card shadow mb-5 rounded border-secondary mb-3">
    <div class="card-header text-center p-3 fw-bolder">
      <%= post.title %>
      <footer class="text-end text-muted fw-light fst-italic"> - <%=User.find_by(id: post.user_id).email %> </footer>

      <!--<blockquote class="blockquote text-center">
        <p class="mb-0"><%= post.title %></p>
        <footer class="blockquote-footer"> <cite title="Source Title">- <%=User.find_by(id: post.user_id).email %></cite></footer>
      </blockquote>-->

    </div>
    <div class="card-body">
      <p class="card-text fw-light"><%= post.content %></p>
      <p class="card-text text-end"><small class="text-muted fw-bold fst-italic">Last updated
       <% t=((Time.now - post.created_at) ).to_i%> 
        <% if (t/(60*60*24)) >1 %>
          <%= (t/(60*60*24)) %> days ago.
        <% elsif (t/(60*60*24)) >0 %>
          <%= (t/(60*60*24)) %> day ago.
        <% elsif (t/(60*60)) >1 %>
          <%= (t/(60*60)) %> hours ago.
        <% elsif (t/(60*60)) >0 %>
          <%= (t/(60*60)) %> hour ago.
        <% elsif t/60 > 1 %>
          <%= (t/60) %> minutes ago.
        <% elsif t/60 > 0 %>
          <%= (t/60) %> minute ago.
        <% else %>  
          <%= t %> seconds ago.
       <% end %>
      </small></p>
    </div>
    <div class="card-footer text-muted">
        <% if user_signed_in? %>
          <% if post.isliked(current_user)%>
            <div style="display: inline-block; float: left;width: 470px">
              <%= button_to "Like", like_path(post), class:"btn btn-sm btn-success", method:"put", disabled: true %>
            </div>
          <% else %>
            <div style="display: inline-block; float: left;width: 470px">
              <%= button_to "Like", like_path(post), class:"btn btn-sm btn-success", method:"put" %>
            </div>
          <% end %>
        <% else %>
          <div style="display: inline-block; float: left;width: 470px">
              <%= button_to "Like", like_path(post), class:"btn btn-sm btn-success", method:"put", disabled: true %>
          </div>
        <% end %>

        <div style="display: inline-block; float:none; ">
          <p class="card-text text-center"><small class="text-muted"> <span class="fw-bold text-success"><%= post.upvotes%></span>  Likes. <span class="fw-bold text-danger"><%= post.downvotes%></span> Dislikes.</small></p>
        </div>

        <% if user_signed_in? %>
          <% if post.isdisliked(current_user) %>
            <div style="display: inline-block; float: right;">
              <%= button_to "Dislike", dislike_path(post), class:"btn btn-sm btn-danger", method:"put", disabled: true %>
            </div>
          <% else %>
            <div style="display: inline-block; float: right;">
              <%= button_to "Dislike", dislike_path(post), class:"btn btn-sm btn-danger", method:"put" %>
            </div>
          <% end %>
        <% else %>
          <div style="display: inline-block; float: right;">
              <%= button_to "Dislike", dislike_path(post), class:"btn btn-sm btn-danger text-end", method:"put", disabled: true %>
          </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= render "home/header" %>
    
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
        
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card shadow mb-5 rounded border-secondary mb-3">  
      <div class="card-header p-3 bg-transparent">
        <div class="field form-group">
          <%= form.text_field :title, class:"form-control fw-bolder", placeholder:"Title" %>
        </div>
      </div>

      <div class="card-body">
        <div class="field form-group">
          <%= form.text_area :content,:cols => "10", :rows => "10", class:"form-control fw-light", placeholder:"Content"   %>
        </div>
        <br/>
        <div class="field form-group">
          <%= form.number_field :upvotes, class:"form-control", placeholder:"Upvotes", value:0, type: :hidden  %>
        </div>
        <div class="field form-group">
          <%= form.number_field :downvotes, class:"form-control", placeholder:"Downvotes",value:0, type: :hidden %>
        </div>
        <div class="field form-group">
          <%= form.number_field :userid, id: :user_post_userid, class:"form-control", value:current_user.id, type: :hidden%>
        </div>
        <div class="actions text-center">
          <%= form.submit  class:"btn btn-success" %>
        <br/>
        </div>
      </div>
     </div> 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class:"btn btn-outline-success btn-sm" %> 
<%= link_to 'Back', posts_path, class:"btn btn-outline-dark btn-sm"  %>

app/views/posts/index.html.erb
<h1>My History</h1>
<br/>
<div class="row">
  <% @posts.each do |post| %>
    <% if current_user.id == post.userid%>
    <div class="col-sm-4">
      <div class="card shadow mb-5 rounded border-secondary mb-3">
        <div class="card-header text-center border-secondary p-3 fw-bolder">
          <%= post.title %>
        </div>
        <div class="card-body">
          <p class="card-text fw-light"><%= post.content %></p>
          <br/>
          <p class="card-text text-end"><small class="text-muted fw-bold fst-italic">Last updated
           <% t=((Time.now - post.created_at) ).to_i%> 
            <% if (t/(60*60*24)) >1 %>
              <%= (t/(60*60*24)) %> days ago.
            <% elsif (t/(60*60*24)) >0 %>
              <%= (t/(60*60*24)) %> day ago.
            <% elsif (t/(60*60)) >1 %>
              <%= (t/(60*60)) %> hours ago.
            <% elsif (t/(60*60)) >0 %>
              <%= (t/(60*60)) %> hour ago.
            <% elsif t/60 > 1 %>
              <%= (t/60) %> minutes ago.
            <% elsif t/60 > 0 %>
              <%= (t/60) %> minute ago.
            <% else %>  
              <%= t %> seconds ago.
           <% end %>
          </small></p>
          <br/>
          <div class="d-grid d-md-block text-center">
              <%= link_to 'Show', post , class:"btn btn-success btn-sm"%>
              <%= link_to 'Edit', edit_post_path(post), class:"btn btn-secondary btn-sm" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'},class:"btn btn-danger btn-sm" %>
          </div>
        </div>
        <div class="card-footer text-muted text-center border-secondary">
          <span>
            <p class="card-text text-center"><small class="text-muted"><span class="fw-bold text-success"><%= post.upvotes%></span>  Likes. <span class="fw-bold text-danger"><%= post.downvotes%></span> Dislikes.</small></p>
          </span>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<%= link_to 'New Post', new_post_path, class:"btn btn-outline-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<br/>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"btn btn-primary"%>

<br/>

app/views/posts/show.html.erb
<div class="card shadow mb-5 rounded border-secondary mb-3">
  <div class="card-header text-center  p-3 fw-bolder">
    <%= @post.title %>
  </div>
  <div class="card-body">
    <p class="card-text fw-light"><%= @post.content %></p>
    <p class="card-text text-end"><small class="text-muted fw-bold fst-italic">Last updated
     <% t=((Time.now - @post.updated_at) ).to_i%> 
      <% if (t/(60*60*24)) >1 %>
        <%= (t/(60*60)) %> days ago.
      <% elsif (t/(60*60*24)) >0 %>
        <%= (t/(60*60)) %> day ago.
      <% elsif (t/(60*60)) >1 %>
        <%= (t/(60*60)) %> hours ago.
      <% elsif (t/(60*60)) >0 %>
        <%= (t/(60*60)) %> hour ago.
      <% elsif t/60 > 1 %>
        <%= (t/60) %> minutes ago.
      <% elsif t/60 > 0 %>
        <%= (t/60) %> minute ago.
      <% else %>  
        <%= t %> seconds ago.
     <% end %>
    </small></p>

    <div class="text-center">
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-success" %>
  </div>
  </div>
  <div class="card-footer text-muted text-center">
    <p class="card-text text-center"><small class="text-muted"> <span class="fw-bold text-success"><%= @post.upvotes%></span>  Likes. <span class="fw-bold text-danger"><%= @post.downvotes%></span> Dislikes.</small></p>
  </div>
</div>

<div class="d-grid gap-3 d-md-block">
  <%= link_to 'Back', posts_path ,class:"btn btn-outline-dark btn" %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.password %><br/>
  <%= user.email %><br/>
<% end %>